# KingdomsAttributes Configuration

snow-kingdom:
  scale: 0.8
  entity_reach: 2.75
  
  # Список игроков-исключений (ники)
  # Эти игроки не получат изменение размера, даже если они в снежном королевстве
  # Ники нечувствительны к регистру
  excluded-players:
    - Erailos_Gray
    - byokinoshojo
    - Finesanti_2013
